### Get all contacts
GET https://chase-pope-341.onrender.com/contacts

###

### Get one contact
GET https://chase-pope-341.onrender.com/contacts/PASTE_ID_HERE

###

### Create a contact
POST https://chase-pope-341.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Chase",
  "lastName": "Pope",
  "email": "chase@example.com",
  "phone": "208-555-1234"
}

###

### Update a contact
PUT https://chase-pope-341.onrender.com/contacts/PASTE_ID_HERE
Content-Type: application/json

{
  "firstName": "Chase",
  "lastName": "Pope",
  "email": "updated@example.com",
  "phone": "208-555-9999"
}

###

### Delete a contact
DELETE https://chase-pope-341.onrender.com/contacts/PASTE_ID_HERE